# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\python\project\ap_remote_monitor\ui\wait_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(268, 159)
        self.label_gif = QtWidgets.QLabel(Form)
        self.label_gif.setGeometry(QtCore.QRect(1, 1, 271, 101))
        self.label_gif.setText("")
        self.label_gif.setObjectName("label_gif")
        self.label_prompt = QtWidgets.QLabel(Form)
        self.label_prompt.setGeometry(QtCore.QRect(40, 110, 191, 31))
        self.label_prompt.setText("")
        self.label_prompt.setObjectName("label_prompt")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "提示"))
